language: c

os:
  - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libjson-c-dev lua5.1 liblua5.1-0-dev
  - sudo apt-get remove libssl-dev

install:
  - git clone https://git.openwrt.org/project/libubox.git
  - pushd libubox && cmake . && make && sudo make install && popd
  - wget https://www.openssl.org/source/openssl-1.0.2n.tar.gz
  - tar zxvf openssl-1.0.2n.tar.gz
  - pushd openssl-1.0.2n &&  ./config --prefix=/usr/local --openssldir=/usr/local/openssl shared && make && sudo make install && popd
  - git clone https://git.openwrt.org/project/ustream-ssl.git
  - pushd ustream-ssl && cmake . && make && sudo make install && popd

script:
  - mkdir build && cd build
  - cmake ..
  - make && sudo make install
