name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Build Directory
      run: mkdir build

    - name: Log Current Working Directory
      working-directory: ./build
      run: pwd

    - name: List Parent Directory's Contents
      working-directory: ./build
      run: ls -liallh ..

    - name: configure
      working-directory: ./build
      run: cmake ..
      
    - name: make
      working-directory: ./build
      run: make
