name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Create Build Directory
      run: mkdir build

    - name: Change To Build Directory
      run: cd build

    - name: Log Current Working Directory
      run: pwd
    - name: List Parent Directory's Contents
      run: ls -liallh ..

    - name: configure
      run: cmake ..
    - name: make
      run: make
